version: '3'
services:
  postgres:
    image: bajuszmate/chaos-stack-tesco_postgres
    build:
      dockerfile: Dockerfile
      context: ./database
  app:
    image: bajuszmate/chaos-stack-tesco_app
    depends_on:
      - postgres
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/go/src/chaos-stack-tesco
    ports:
      - '5500:5500'
    environment:
      - PORT=5500
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
